### PR TITLE
Template Update with some perks

### PR DESCRIPTION
**Pull request by chez14**
As emailed on the Mailing List, our Thesis Coordinator lecturer gave updates via email, a few weeks before the finalization of current thesis begins. One of the step states that we shall update the template to this new template.

Also, the perks. I renamed the `LICENSE.md` file to `LICENSE` to prevent weird text wrapping and markdown miss-parsing as the file is intended to be viewed as plain text, instead of markdown.

That being said, here's the summary of "in this PR":
- Renamed `LICENSE.md` to `LICENSE`, and also updated the `README.md` to accomodate the changes.
- Updated skripsi template to use the current one from Overleaf.

Thanks~!

### CODE REVIEW

**Comment by pascalalfadian** [comment]
Thanks @chez14! Sorry for late response, as the Windows mail retrieval didn't work well in the past few days. Looks good, but can you please revert the file permissions back from 755 to 644? You may need Linux box to do this.

**Review by pascalalfadian — CHANGES_REQUESTED** [review]
Thanks @chez14! Sorry for late response, as the Windows mail retrieval didn't work well in the past few days. Looks good, but can you please revert the file permissions back from 755 to 644? You may need Linux box to do this.

**Comment by chez14** [comment]
Hi Ko @pascalalfadian,

I've updated the file permission as requested ya. Thank you.

**Comment by pascalalfadian** [comment]
Cool, thank you very much!

**Pull request merged**
